project_id = "dxkzktkeagpddmpcyooe"

[functions.bunny-create-upload]
verify_jwt = false

[functions.bunny-video-status]
verify_jwt = false

[functions.bunny-delete-video]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.ai-generate-questions]
verify_jwt = false
